DROP DATABASE ejemplo80640;
CREATE DATABASE ejemplo80640;

USE ejemplo80640;

CREATE TABLE usuario(
	id INT AUTO_INCREMENT NOT NULL,
    nombre VARCHAR(30) NOT NULL,
    pass VARCHAR(30) NOT NULL,
    PRIMARY KEY (id)
);